# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions - update workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  # Go modules - for all Go CLI tools and libraries
  - package-ecosystem: "gomod"
    directory: "/" # Adjust if your Go code lives in subdirs like /cmd/tool or /tools/chartpress
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      go-deps:
        patterns:
          - "*"

  # Python pip - for automation and project generators
  - package-ecosystem: "pip"
    directory: "/scripts" # Adjust based on your folder structure
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      python-deps:
        patterns:
          - "*"

  # Docker - containerized services like image resizer
  - package-ecosystem: "docker"
    directory: "/docker/image-resizer" # Adjust based on project folder
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Helm - for umbrella/subchart systems
  - package-ecosystem: "helm"
    directory: "/charts" # Or "/" if charts live at the repo root
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      helm-deps:
        patterns:
          - "*"
